### PR TITLE
graceful deprecation of Django 1.6 and 1.7

### PR DESCRIPTION
**Pull request by brunobord**
refs #9

### CODE REVIEW

**Comment by brunobord** [comment]
mmmm... need to investigate, I don't see the deprecation warning in django1.7 jobs.

**Comment by brunobord** [comment]
extract from Travis output:

### Django 1.6:

```
py27-django16 runtests: commands[2] | rundemo test demo_chunkator
/home/travis/build/novafloss/django-chunkator/chunkator/__init__.py:15: PendingDeprecationWarning: Django 1.7 and lower versions will soon be deprecated. Please upgrade.
  PendingDeprecationWarning
Creating test database for alias 'default'...
.......
```

### Django 1.7

```
py27-django17 runtests: commands[2] | rundemo test demo_chunkator
/home/travis/build/novafloss/django-chunkator/chunkator/__init__.py:15: PendingDeprecationWarning: Django 1.7 and lower versions will soon be deprecated. Please upgrade.
  PendingDeprecationWarning
Creating test database for alias 'default'...
.......
```

### Django 1.8 (no warning)

```
py27-django18 runtests: commands[2] | rundemo test demo_chunkator
Creating test database for alias 'default'...
.......
```

**Comment by brunobord** [comment]
OPR.

**Comment by wo0dyn** [comment]
LGTM. 👍

**Pull request merged**
