### PR TITLE
Add a FAQ section to the README

### PR DESCRIPTION
**Pull request by pmourlanne**
Hello there :wave: 

I think the answer to https://github.com/peopledoc/django-chunkator/issues/39 (and to a lesser extent https://github.com/peopledoc/django-chunkator/issues/38) is very important for people deciding if they want to use django-chunkator.\
I think they deserve a place in the README: I created a FAQ section and basically copy pasted Yannick's answers.

Signed: someone who's going to install django-chunkator in their project, based on the answer to #38 :heart:

### CODE REVIEW

**Review by ewjoachim — APPROVED** [review]

**Comment by ewjoachim** [comment]
Splendid ! Thanks a lot for your contribution ! And welcome to the project :)

**Review by brunobord — APPROVED** [review]
<3

**Comment by ewjoachim** [comment]
@pmourlanne What's your opinion on making a release with this, which would make your FAQ appear in PyPI? On a scale from meh to must ?

**Comment by pmourlanne** [comment]
@ewjoachim I don't really care :O It's more of a long term issue too so it can probably wait for the next "natural" release :)

**Pull request merged**
