### PR TITLE
Fixed PendingDeprecationWarning

### PR DESCRIPTION
**Pull request by lorenzomorandini**
Fixed PendingDeprecationWarning by changing "raise StopIteration" with "return -1" as noticed in issue https://github.com/peopledoc/django-chunkator/issues/23

### CODE REVIEW

**Comment by brunobord** [comment]
Thank you for your patch, but a few issues here:

1. why a ``return -1`` here? wouldn't a simple ``return`` be enough?
2. it breaks the Python 2.7 tests, as you can see here: https://travis-ci.org/peopledoc/django-chunkator/jobs/371450873

**Comment by lorenzomorandini** [comment]
Should be fixed, let me know.

**Comment by lorenzomorandini** [comment]
Any news?

**Comment by brunobord** [comment]
sorry, I was a AFK for a few days/weeks now. I'll try to catch up as fast as I can! :o)

**Pull request closed without merging**
